services:
  - type: web
    name: guild-manager-backend
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build && npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.byxdneprmynjwbxsrnop:b4PZevKB7NpjHn@aws-1-eu-west-3.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: DIRECT_URL
        value: postgresql://postgres.byxdneprmynjwbxsrnop:b4PZevKB7NpjHn@aws-0-eu-west-3.pooler.supabase.com:5432/postgres
      - fromGroup: guild-manager-secrets
